#!/bin/bash
get_dims() {
    temp_rows="temp_rows_file$$"
    temp_cols="temp_cols_file$$"
    lines=0
    columns=0
    while read line
    do
        lines=$(( lines + 1 ))
        columns_in_line=0
        for number in $line
        do
            columns_in_line=$(( columns_in_line + 1 ))
        done
        columns=$columns_in_line
    done < $1
    echo $lines > $temp_rows
    echo $columns > $temp_cols
}

dims() {
    return=0
    if [ $2 ]
    then
        echo "Only one argument allowed" >&2
        return=2
    elif [ ! -f "$1" ]
    then
        echo "Cannot read file $1" >&2
        return=1
    else
        get_dims $1
        temp_rows="temp_rows_file$$"
        temp_cols="temp_cols_file$$"
        read -r rows < $temp_rows
        read -r cols < $temp_cols
        echo "$rows $cols"
        rm $temp_rows
        rm $temp_cols
    fi
    return $return
}
dims $1 $2