#!/bin/bash
get_dims() {
    temp_rows="temp_rows_file$$"
    temp_cols="temp_cols_file$$"
    lines=0
    columns=0
    while read line
    do
        lines=$(( lines + 1 ))
        columns_in_line=0
        for number in $line
        do
            columns_in_line=$(( columns_in_line + 1 ))
        done
        columns=$columns_in_line
    done < $1
    echo $lines > $temp_rows
    echo $columns > $temp_cols
}

transpose() {
    return=0
    if [ $2 ]
    then
        echo "Only one argument allowed" >&2
        return=2
    elif [ ! -f "$1" ]
    then
        echo "Cannot read file $1" >&2
        return=1
    else
        get_dims $1
        temp_rows="temp_rows_file$$"
        temp_cols="temp_cols_file$$"
        read -r rows < $temp_rows
        read -r cols < $temp_cols
        rm $temp_rows
        rm $temp_cols
        temp_col="temp_col_file$$"
        temp_row="temp_row_file$$"
        temp_output="temp_output"
        for (( i=1; i<=$cols; i++ ))
        do
            cut -f $i $1 > $temp_col
            col_counter=1
            while read row
            do
                if [ $col_counter -eq 1 ]
                then
                    echo -n $row > $temp_row
                else
                    echo -n $row >> $temp_row
                fi
                if [ ! $col_counter -eq $rows ]
                then
                    echo -e -n "\t" >> $temp_row
                fi
                col_counter=$(( col_counter + 1 ))
            done < $temp_col
            if [ $i -eq 1 ]
            then
                cat $temp_row > temp_output
            else
                cat $temp_row >> temp_output
            fi
            if [ ! $i -eq $cols ]
            then
                echo -e $"\r" >> $temp_output
            fi
        done
        cat $temp_output
        rm $temp_col
        rm $temp_row
        rm $temp_output
    fi
    return $return
}
transpose $1 $2